name: Get Currencies

# This workflow is triggered on pushes to the master branch
on:
  pull_request:

jobs:
  update-currencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Bonbast
        run: pip install -U bonbast

      - name: Export Currencies Data to JSON
        run: |
          for i in {1..3}; do
              python -m bonbast export --pretty > currencies.json && break || sleep 10
          done
          cat currencies.json

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add currencies.json
          git commit -m "Update currencies data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}