name: Get Currencies

# This workflow is triggered on pull requests.
on:
  pull_request:

jobs:
  update-currencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Bonbast
        run: pip install -U bonbast

      - name: Export Currencies Data to JSON
        run: python -m bonbast export --pretty > currencies.json && cat currencies.json
        with:
          timeout-minutes: 5
          max-attempts: 3

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add currencies.json
          git commit -m "Update currencies data"
          git push origin HEAD:${GITHUB_REF#refs/heads/} 
