name: build

on:
  push:
    branches:
      - develop
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Check Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Detekt Check & Auto Correct
        run: ./gradlew detekt --auto-correct

  unit-tests:
    needs: check
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Tests
        run: ./gradlew testDebugUnitTest

  androidTest:
    needs: check
    name: Instrumented tests
    runs-on: macOS-12
    strategy:
      matrix:
        device-config: [ "pixel6api31" ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Run instrumented tests with GMD
        run: ./gradlew cleanManagedDevices --unused-only &&
          ./gradlew ${{ matrix.device-config }}paxDebugAndroidTest -Dorg.gradle.workers.max=1
          -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-${{ matrix.api-level }}
          path: '*/build/reports/androidTests'